sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "8"
  - "10"
  - "12"
env:
  matrix:
    - TEST_SUITE=unit
matrix:
  include:
    - node_js: "lts/*"
      env: TEST_SUITE=lint
script: npm run $TEST_SUITE
