sudo: false
language: node_js
node_js:
  - "lts/*"
  - "8"
  - "10"
  - "node"
env:
  matrix:
    - TEST_SUITE=unit
matrix:
  include:
    - node_js: "lts/*"
      env: TEST_SUITE=lint
script: npm run $TEST_SUITE
