sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
env:
  matrix:
    - TEST_SUITE=unit
matrix:
  include:
    - node_js: "4"
      env: TEST_SUITE=lint
script: npm run $TEST_SUITE
