name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Restore node_modules cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Run tests
        run: npm run unit

  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Restore node_modules cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Run lint command
        run: npm run lint
